# 422 - digitos insuficientes
GET http://localhost:8000/temperatura/123

###

# 422 - caracteres invalidos
GET http://localhost:8000/temperatura/0123-567

###

# 404
GET http://localhost:8000/temperatura/12345678

###

# 200
GET http://localhost:8000/temperatura/22460900